"""add unit sale workflow

Revision ID: 93ac8fad3497
Revises: f4c9d2e8a1b7
Create Date: 2026-08-07 11:12:13.035318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ac8fad3497'
down_revision = 'f4c9d2e8a1b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('buyer_party_id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('cheque_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cheque_count >= 0', name='ck_unit_sales_cheque_count_non_negative'),
    sa.CheckConstraint('down_payment <= sale_price', name='ck_unit_sales_down_payment_le_price'),
    sa.CheckConstraint('down_payment >= 0', name='ck_unit_sales_down_payment_non_negative'),
    sa.CheckConstraint('sale_price > 0', name='ck_unit_sales_price_positive'),
    sa.ForeignKeyConstraint(['buyer_party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id')
    )
    op.create_index(op.f('ix_unit_sales_project_id'), 'unit_sales', ['project_id'], unique=False)
    op.create_table('sale_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['unit_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_sale_id'), 'transactions', ['sale_id'], unique=False)
    op.create_foreign_key('transactions_sale_id_fkey', 'transactions', 'unit_sales', ['sale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_sale_id_fkey', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_sale_id'), table_name='transactions')
    op.drop_column('transactions', 'sale_id')
    op.drop_table('sale_attachments')
    op.drop_index(op.f('ix_unit_sales_project_id'), table_name='unit_sales')
    op.drop_table('unit_sales')
    # ### end Alembic commands ###
