"""add source transaction id

Revision ID: c158f0b2f327
Revises: 2a8e3f1c4b5d
Create Date: 2026-07-30 23:11:16.298103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c158f0b2f327'
down_revision = '2a8e3f1c4b5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('source_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transactions', ['source_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'source_transaction_id')
    # ### end Alembic commands ###
